
/* ================================================================ *
 *          Automatically generated by n-Blocks Studio 2.0          *
 *                                                                  *
 *                         www.n-blocks.net                         *
 * ================================================================ */
#include "nlib\nblocks.h"
// #include "nlib\BSP\bsp.h"
// Custom nodes:
#include "nlib\KernelFramePulse\kernelframepulse.h"
#include "nlib\Ticker\ticker.h"
#include "nlib\ADC\adc.h"
#include "nlib\KalmanSimple\KalmanSimple.h"
#include "nlib\StringSerial\stringserial.h"
#include "nlib\StringFormat\stringformat.h"

// -*-*- List of node objects -*-*-
nBlock_KernelFramePulse      nb_nBlockNode1_KernelFramePulse (LED4);
nBlock_Ticker                nb_nBlockNode2_Ticker           (200);
nBlock_ADC                   nb_nBlockNode3_ADC              (p20, OUTPUT_TYPE_FLOAT);
nBlock_KalmanSimple          nb_nBlockNode4_KalmanSimple     (2.0, 2.0, 0.01);
nBlock_StringSerial          nb_nBlockNode5_StringSerial     (USBTX, USBRX);
nBlock_StringFormat          nb_nBlockNode6_StringFormat     ("ADC = %f \r\n");

// -*-*- List of connection objects -*-*-
nBlockConnection    n_conn0( &nb_nBlockNode6_StringFormat,     0,    &nb_nBlockNode5_StringSerial,     0);
nBlockConnection    n_conn1( &nb_nBlockNode4_KalmanSimple,     0,    &nb_nBlockNode6_StringFormat,     0);
nBlockConnection    n_conn2( &nb_nBlockNode3_ADC,              0,    &nb_nBlockNode4_KalmanSimple,     0);
nBlockConnection    n_conn3( &nb_nBlockNode2_Ticker,           0,    &nb_nBlockNode3_ADC,              0);


// -*-*- Main function -*-*-
int main(void) {
    SetupWorkbench();
    while(1) {
        ProgressNodes();
        
        // Your custom code here!
    }
}
